### ISSUE TITLE
Nova crashes when attempting to save project on Windows 10

### ISSUE THREAD

**Issue by timur-almaev** [hcmlab/nova#357] opened 2018-02-15 15:13 UTC
Hi, when I try to save previously loaded project composed of a video and some annotations Nova crashes. Do you know what can possibly be causing this? Thanks.

**Comment by tobiasbaur** [comment] 2018-02-16 08:39
Hello,

I tried and could'nt reproduce your problem. 
Can you give more details? are you using files from file system or from database? What files have you loaded? what version are you using?

**Comment by timur-almaev** [comment] 2018-02-17 00:28
Hi, thanks for the prompt reply. It happens when I load the video from a file, create some annotations, then save the project, then close the program, re-open it to continue working on the project, then when I try to save the project again it crashes. I'm using a binary version 1.0.1.8. The video is an .mp4 h264 file. Thanks!

**Comment by tobiasbaur** [comment] 2018-02-20 09:42
I tried again to follow your steps, yet no crash here. Can anyone else confirm this issue? Is it possible there is some limitation from your Windows concerning the location where you want to save the project? Can you attach a "broken" project file?

**Comment by timur-almaev** [comment] 2018-02-21 19:48
I'm in Germany at the moment, it'll be hard for me to try it on different computers. I guess we'll just see each other in Luxembourg and see what can be causing this. Thanks!

**Comment by tobiasbaur** [comment] 2018-02-28 22:37
As cleared today, this had to do with something else and is actually not a bug, so I'll close the issue for now.

**Closed by tobiasbaur** 2018-02-28 22:37 UTC
Labels: bug
